### ISSUE TITLE
Getting Influx error code 500

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/galloper#115]
I am getting error code 500 for influx db,
![image](https://user-images.githubusercontent.com/3865402/96132504-6425b780-0ef2-11eb-9d17-c2b3ac3fd953.png)

please find the below snapshot for influx 500 error 
![image](https://user-images.githubusercontent.com/3865402/96132251-16a94a80-0ef2-11eb-8424-ec6d39f59630.png)

**Comment by hunkom** [comment]
Hi @tokarthik 
how do you run the test? Could you share configs from test planner?

**Comment by tokarthik** [comment]
thanks, i think its problem with the disk full issue , let me comeback

**Comment by tokarthik** [comment]
Due to reinstall because of disk space issue. not able to reproduce it
