### ISSUE TITLE
Grafena is missing after update

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/galloper#116]
I have reinstalled the system due to disk issue seems like Grafana is missing
![image](https://user-images.githubusercontent.com/3865402/96256316-57679900-0fb0-11eb-8a1d-9a528f7ee597.png)

**Comment by arozumenko** [comment]
This is expected behavior.
Grafana going to be restricted only for specific group (grafana) in Keycloak

**Comment by tokarthik** [comment]
@arozumenko i have created a group called grafana and created grafana user still its not showing !
