### ISSUE TITLE
Not able to get the result 

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/galloper#120]
I have installed a fresh new updated version due to some data issue.

I have followed your steps like
create superuser and added role as well
created secret as well
![image](https://user-images.githubusercontent.com/3865402/96617247-480f8500-12fb-11eb-94b5-b3d7710da65d.png)

Seems like tasks not having any log

![image](https://user-images.githubusercontent.com/3865402/96617379-768d6000-12fb-11eb-8789-f144b83c8e47.png)

backend logs 
![image](https://user-images.githubusercontent.com/3865402/96617456-8dcc4d80-12fb-11eb-8303-bd35c44dc368.png)

**Comment by tokarthik** [comment]
added browser logs

![image](https://user-images.githubusercontent.com/3865402/96618497-ef40ec00-12fc-11eb-93e2-58390e0896c9.png)

**Comment by arozumenko** [comment]
@tokarthik this is planned to be fixed today

**Comment by tokarthik** [comment]
> @tokarthik this is planned to be fixed today

thanks @arozumenko

**Comment by tokarthik** [comment]
any update @arozumenko

**Comment by hunkom** [comment]
@tokarthik did you generate auth token in the secrets?

**Comment by tokarthik** [comment]
yes I did create

**Comment by tokarthik** [comment]
i have checked in the secret its not there again i try to create but not able to add to secrets

![image](https://user-images.githubusercontent.com/3865402/97193958-7da3ea80-17a1-11eb-9ecd-609e361a92e2.png)

**Comment by hunkom** [comment]
Did you use getcarrier/installer container to install Carrier? (If so did you pull latest docker container?)
Or you have installed it manually? (if so did you pull fresh code from carrier-io repo?) 
Could you share documents/guides on carrier installation that you used?

**Comment by tokarthik** [comment]
i have used carrier-io/dev and used docker-compose -d up

**Comment by tokarthik** [comment]
now i have treid 'docker-compose pull and git pull '

![image](https://user-images.githubusercontent.com/3865402/97210190-227bf300-17b5-11eb-8934-1bb1d4dac3bb.png)

**Comment by hunkom** [comment]
The installation scripts in **carrier-io/dev** folder are a bit outdated, so it is difficult to identify the problem. You can reinstall Carrier using this folder - **installation_scripts/no_ssl** to get the latest version (make sure you have pulled the latest version from git repo).

There are some documentation:
https://github.com/carrier-io/carrier-io/wiki/Quick-Start
https://github.com/carrier-io/carrier-io/wiki/Project-And-Users
https://github.com/carrier-io/carrier-io/wiki/Backend-Performance-Test-Planner

**Comment by tokarthik** [comment]
Thanks @hunkom i have installed as you mentioned above and followed all steps 

![image](https://user-images.githubusercontent.com/3865402/97241836-28d89200-17ea-11eb-8fe8-181c0538d879.png)


![image](https://user-images.githubusercontent.com/3865402/97241938-69381000-17ea-11eb-8290-beaa4efce891.png)


![image](https://user-images.githubusercontent.com/3865402/97241972-840a8480-17ea-11eb-81c3-548b7b445304.png)


![image](https://user-images.githubusercontent.com/3865402/97241993-9389cd80-17ea-11eb-8a70-e69ba92c12fb.png)

seems like post-process having some issue

**Comment by hunkom** [comment]
@tokarthik are there any reports on the reports page in galloper? Can you get the results?

**Comment by tokarthik** [comment]
more than 12 hrs it still in progress i tried to cancel but no result 

![image](https://user-images.githubusercontent.com/3865402/97284760-54369d80-1839-11eb-8c28-e89a0dc09bca.png)

![image](https://user-images.githubusercontent.com/3865402/97284675-408b3700-1839-11eb-92bb-8b437a87e6e4.png)

**Comment by hunkom** [comment]
Did you run **bootstrap.sh** after _docker-compose up -d_? It should create InfluxDB user and necessary databases. First, you need to modify **bootstrap.sh** by replacing **INFLUXPASSWORD** with your **INFLUX_PASSWORD** from **.env** file.

**Comment by tokarthik** [comment]
i got this error 
![image](https://user-images.githubusercontent.com/3865402/97297086-720bfe80-1849-11eb-9d78-3de257bbb5d9.png)

**Comment by hunkom** [comment]
Seems like there is a typo in the commands that create databases in InfluxDB. The commands should look like:
To create influx db user
**_docker exec carrier-influx bash -c "influx -execute \"create user admin with password 'password' with all privileges;\""_** 
Single quotes are required only for password
To create databases
**_docker exec carrier-influx bash -c "influx -username 'admin' -password 'password' -execute 'create database jmeter'"_**
Single quotes are required for username and password

**Comment by tokarthik** [comment]
thanks @hunkom 
redeployed again and tried 
i have used the bootstrap to run the first time it ran but can't see any DB created hence ran it again 

![image](https://user-images.githubusercontent.com/3865402/97302398-ec8c4c80-1850-11eb-95dd-c9d6039a669d.png)

**Comment by tokarthik** [comment]
tried in commandline as you suggested 
![image](https://user-images.githubusercontent.com/3865402/97302732-5c9ad280-1851-11eb-825b-052aefc053ce.png)

**Comment by tokarthik** [comment]
@hunkom thanks a lot it seems like working whenever i ran bootstrap it will create all  but it's not shown in the commanline
