### ISSUE TITLE
RP option shows only on backend performance testing 

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/galloper#127]
I am not sure its the design or bug 

I can see only backend performance testing having RP integration option 

![image](https://user-images.githubusercontent.com/3865402/97320806-1b60ed80-1866-11eb-973b-21aa22132a57.png)

It's missing on the UI Frontend testing, SAST and DAST

![image](https://user-images.githubusercontent.com/3865402/97320949-41868d80-1866-11eb-86be-ded579f3f32d.png)

![image](https://user-images.githubusercontent.com/3865402/97321055-5f53f280-1866-11eb-8326-5209b3abed59.png)

![image](https://user-images.githubusercontent.com/3865402/97321129-7397ef80-1866-11eb-8db8-acea95dd6d6c.png)

**Comment by tokarthik** [comment]
@hunkom is this as designed?

**Comment by hunkom** [comment]
@tokarthik at the moment only backend performance testing has RP integration. For DAST and SAST will be added soon
