### ISSUE TITLE
Reportportal- have only one launch name for all the test execution

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/galloper#136]
I have created multiple tests and try to get the result but all comes as one launch name,
i would suggest each project name used as a lunch name 

![image](https://user-images.githubusercontent.com/3865402/98670068-0c8c3780-234a-11eb-9590-b709d69d36a9.png)

**Comment by hunkom** [comment]
@tokarthik you can configure launch name

https://github.com/carrier-io/carrier-io/wiki/Integrations.-Report-Portal

**Comment by hunkom** [comment]
The next release will add the ability to customize launch name for each test. At the moment, you can set up only at the project level on the secrets page (rp_perf_api secret).
