### ISSUE TITLE
how to increase test runner

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/galloper#137]
As default, I can run max 2 runners only, how to increase the runners

**Comment by tokarthik** [comment]
`

20-Nov-12 12:10:42 | START RequestId: 93f88e18-cf4b-1c9f-5b92-9a29becb7905 Version: $LATEST Total Workers: 2 Available Workers: 2 We are unable to process your request due to limited resources. We have 2 available END RequestId: 93f88e18-cf4b-1c9f-5b92-9a29becb7905 REPORT RequestId: 93f88e18-cf4b-1c9f-5b92-9a29becb7905 Init Duration: 122.34 ms Duration: 3419.04 ms Billed Duration: 3500 ms Memory Size: 1536 MB Max Memory Used: 39 MB   {"statusCode":500,"body":"Traceback (most recent call last):\n  File \"/var/task/lambda.py\", line 96, in handler\n    _start_and_track(args)\n  File \"/var/task/control_tower/run.py\", line 604, in _start_and_track\n    groups, test_details = start_job(args)\n  File \"/var/task/control_tower/run.py\", line 334, in start_job\n    celery_connection_cluster[str(channel)]['app'] = connect_to_celery(concurrency_cluster[str(channel)], channel)\n  File \"/var/task/control_tower/run.py\", line 291, in connect_to_celery\n    exit(1)\n  File \"/var/lang/lib/python3.7/_sitebuiltins.py\", line 26, in __call__\n    raise SystemExit(code)\nSystemExit: 1\n"}
-- | --


`

**Comment by hunkom** [comment]
@tokarthik by default there are 2 runners available to execute a test from the instance where Carrier is deployed. 
To increase number of runners you need to run getcarrier/interceptor container on load generator instance. Please check documentation (Configuration of interceptor (scale unit))

https://github.com/carrier-io/carrier-io/wiki/Quick-Start

**Comment by tokarthik** [comment]
thanks @hunkom
