### ISSUE TITLE
getting grid-router-nossl\" error: port is missing" 

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/galloper#140]
after upgraded latest, i found this error and not sure how its coming 

carrier-traefic | time="2020-11-19T23:35:20Z" level=error msg="service \"grid-router-nossl\" error: port is missing" providerName=docker container=grid-router-nossl-6284036e604fee51c9ff3cb2e60ff7aa4a137627e8c38d925a0448ce003bf484

**Comment by tokarthik** [comment]
@hunkom any suggestion regarding the above issue

**Comment by arozumenko** [comment]
@tokarthik does it still actual?
