### ISSUE TITLE
Galloper & 'Active Directory group' integration issue

### ISSUE THREAD

**Issue by kostiantyn-yarovyi** [carrier-io/galloper#153]
After you integrated KeyCloak with AD it may appear, that users (from AD) are parts of different preconfigured groups.
At the same time, from Galloper perspective user can have only 'integer' group name (correspond to project ID) or specific one 'superadmin'.

As a part of 'project retrieving' logic we are trying to query all 'projects' assigned to the user through groups from the KeyCloak.

### Steps to reproduce

1. In Galloper, under 'superadmin' create new project

2. In KeyCloak create groups with names: '<id_of_the_project_from_first_step>', 'testGroupName'

3. In KeyCloak create new user and assigned two groups mentioned in previous step

4. Enter Galloper UI using user from previous step

### Actual result:

- Project not displayed. In browser dev tools observe 2 requests with HTTP response code '500'

### Expected result:

- Projects successfully loaded. No errors in dev tools

### Dev investigation results:
Calculation of available 'projects' for end user strictly connected to the 'groups' assigned to the user in KeyCloak. Basically, logic parse all groups assigned to user, and expect 2 types of groups:
1. Numeric IDs (correspond to project ID)
2. 'superadmin' - specific hardcoded group name from.

After we retrieved & parsed group names system creates 'filter', that will be applied to the DB query, that will retrieve actual projects from Postgres.
![image](https://user-images.githubusercontent.com/96446635/146835729-974dcfdf-a39d-445f-97e8-183b9db77310.png)

In production we faced with next situation -> Carrier KeyCloak integrated with customer's Active Directory, and users in AD has different internal 'groups' assigned to them. Almost all of them are not 'numeric' or 'superadmin'.
As the result, we are trying to pass into **'Int'** filter 'non-int' values 
SQL representation is:

> 'SELECT * FROM projects WHERE id IN (1, 'testGroupName')

At this point SQL driver will raise an exception and on the UI we will see '500' status code.

**Comment by hunkom** [comment]
Pull request merged. 
You can pull updated docker image with "docker pull getcarrier/galloper:2.5"
