### ISSUE TITLE
Do not publicly expose git credentials on the UI for backend performance tests

### ISSUE THREAD

**Issue by kostiantyn-yarovyi** [carrier-io/galloper#155]
### Steps to reproduce:
1. Open 'Tests Planner' ->  'Backend Performance'
2. Click 'Add Performance Tests' and fill in all required fields, including configuration for Git (Repo URL, username, password)
3. Reload page/log under other users & observe created 'Performance tests' details

### Actual result:
'Git user password' published as an plain text & and viewable by anyone, who can login

### Expected result:
 Since password is sensitive information it should be masked

**Comment by arozumenko** [comment]
Rhis is as designed.
You should use project secrets to store passwords and do not expose them in
any of configurations.
Planner should have {{secrets.password}} or whatever you will call that
secret. which is not sensitive and should not be masked

**Comment by kostiantyn-yarovyi** [comment]
Thanks for provided information, still since UI provides such options, customer unfortunately may ignore given recommendations. 
After conversation with Mykhailo Hunko, we found out how we can address the issue. Changes you can find in linked pull request
