### ISSUE TITLE
Not able to add project

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/galloper#73]
I have installed on AWS able to connect carrier or user but not able to add a project in the carrier.io

![image](https://user-images.githubusercontent.com/3865402/90864884-6869a480-e389-11ea-8826-a681f1ca40b1.png)

**Comment by arozumenko** [comment]
@tokarthik  what installation steps have you used?
In case you done it manually, I'd suggest to create superuser group and add user to that group in Keycloak.
Only superusers are allowed to create projects

**Comment by tokarthik** [comment]
@arozumenko thanks for your swift reply , i have installed manually using docker-compose ,
let me create superuser group in keycloak

**Comment by tokarthik** [comment]
@arozumenko i have created super admin and gave all the access as below still no luck 

![image](https://user-images.githubusercontent.com/3865402/90892002-800a5280-e3b4-11ea-8ea0-0ee6e4804743.png)
 
error snapshot 
![image](https://user-images.githubusercontent.com/3865402/90892117-b778ff00-e3b4-11ea-8429-522e65bbf5a2.png)

**Comment by tokarthik** [comment]
@arozumenko am I missing anything?
thanks in advance

**Comment by arozumenko** [comment]
@tokarthik 

In user groups you need to create group superadmin
![Screen Shot 2020-08-21 at 4 36 21 PM](https://user-images.githubusercontent.com/6542858/90896588-96bca380-e3cc-11ea-9520-3520ffe3e870.png)

After that, add user to that group
![Screen Shot 2020-08-21 at 4 37 53 PM](https://user-images.githubusercontent.com/6542858/90896656-b2c04500-e3cc-11ea-9825-aa8c6c04618b.png)

This is pretty much it

**Comment by tokarthik** [comment]
perfect it worked thanks, now i am trying to test but cant see any test result or even status but I will open another issue soon
