### ISSUE TITLE
performance test result not sent to RP Reportportal

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/galloper#75]
i am able to see the test run in the report section but can't able to get it to RP

![image](https://user-images.githubusercontent.com/3865402/91074941-311f2000-e635-11ea-9a3f-d5df3d9daeb8.png)

is there ahttps://github.com/tokarthiknything I have set up other than the below section 

![image](https://user-images.githubusercontent.com/3865402/91075341-d4703500-e635-11ea-8c67-8d6fee56f7c8.png)

after clicking test nothing happened but once clicked save got the jira setup appeared in the background 
![image](https://user-images.githubusercontent.com/3865402/91075511-17caa380-e636-11ea-8085-e80774bea66d.png)

closed the front popup and got the below popup screen for JIRA setup 

![image](https://user-images.githubusercontent.com/3865402/91075462-0386a680-e636-11ea-82d0-8a8584a7360f.png)

**Comment by hunkom** [comment]
@tokarthik Report Portal integration as well as ADO integration is in the backlog for now. You can use Jira integration or SMTP.

**Comment by tokarthik** [comment]
thanks

**Comment by tokarthik** [comment]
RP integration is the main feature for me :-)

**Comment by karthikeyans1** [comment]
@hunkom  any ETA for RP integration .Is there anything I can contribute to get it expediate

**Comment by arozumenko** [comment]
@tokarthik @karthikeyans1 RP is there in latest builds, please verify

**Comment by karthikeyans1** [comment]
let me verify , due to some issue I am updating the version .

**Comment by tokarthik** [comment]
I have tested with the latest version but no luck

**Comment by tokarthik** [comment]
ignore the above comment, seems like the test itself not ran let me fix that issue and test again

**Comment by tokarthik** [comment]
i have run the test after RP integrated but cant see any report 
post processer having issue i have mentioned in carrier-io this issue

![image](https://user-images.githubusercontent.com/3865402/97243460-4f003100-17ee-11eb-9ff1-3ce920bacf46.png)

**Comment by tokarthik** [comment]
updated latest version today and working fine with RP v5

**Comment by vijaymishra-dan** [comment]
Hi tokarthik, can you help me to set up the Carrier.io in Report portal and JMeter
