### ISSUE TITLE
not able to see any dashboard in grafana

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/galloper#77]
i have successfully installed and ran the performance test using JMeter but can't able to see any dashboard in grafana

do I need to set up manually if yes please  share the document how to setup 
![image](https://user-images.githubusercontent.com/3865402/91424130-4f616780-e851-11ea-88de-bf3f59bc4eb2.png)

**Comment by hunkom** [comment]
Hi @tokarthik 
Yes, you can set up all the necessary dashboards manually. Dashboards you can find in carrier-io repo:
https://github.com/carrier-io/carrier-io/tree/master/grafana_dashboards
Also there is a guide how to do it:
https://github.com/carrier-io/carrier-io/wiki/Performance-Testing.-Results-Analysis

You need to login as superadmin user to set up dashboards

**Comment by tokarthik** [comment]
@hunkom thanks i have to manage to setup dashboard but can't find an import option data source

**Comment by hunkom** [comment]
you can create data sources manually as well. You can find it in the guide I provided you
<img width="243" alt="Screenshot 2020-08-27 at 16 56 18" src="https://user-images.githubusercontent.com/46744804/91451701-5a82ba80-e886-11ea-82eb-e8001161da5d.png">

**Comment by tokarthik** [comment]
@hunkom in that wiki screenshot is missing 

https://github.com/carrier-io/carrier-io/issues/46

![image](https://user-images.githubusercontent.com/3865402/91976895-9c45b200-ed19-11ea-93bb-da5207619674.png)

**Comment by tokarthik** [comment]
I have set up all data sources and import the JSON file but can't see any dashboard imported 

![import](https://user-images.githubusercontent.com/3865402/91992292-e041b280-ed2b-11ea-902c-fd613dacaadf.gif)

**Comment by hunkom** [comment]
did you remove "dashboard" key from json?

**Comment by tokarthik** [comment]
no @hunkom  i just used as it is

**Comment by hunkom** [comment]
you need to remove the "dashboard" key and its closing brackets from the dashboard JSON-file.

<img width="905" alt="Screenshot 2020-09-02 at 18 05 03" src="https://user-images.githubusercontent.com/46744804/92000995-d5484b80-ed46-11ea-9e60-d0bcce35ad00.png">

**Comment by tokarthik** [comment]
sure let me try @hunkom

**Comment by arozumenko** [comment]
hi @tokarthik, any progress on that?

**Comment by tokarthik** [comment]
yes thanks its working
