### ISSUE TITLE
Unable to Edit Performance Tests

### ISSUE THREAD

**Issue by ankitps1807** [carrier-io/galloper#78]
I am trying to edit the performance tests created, however when the Edit button is clicked at the bottom of the test page it results in going back to the Backend Tests page.

**Comment by hunkom** [comment]
@ankitps1807 First, you need to fill in all the parameters in the test that you want to add/change. Then click the Edit button to save them.

**Comment by karthikeyans1** [comment]
we did tried @hunkom  but its opening the new window

**Comment by hunkom** [comment]
That's right, Edit button is to save your test config changes and it should redirect you to the Backend Tests page. So it's not an issue. You have to set up some parameters and then click this button. After that you can open your test and check if your changes were saved.

**Comment by ankitps1807** [comment]
Hi @hunkom I am able to edit in the way you have suggested above in MS Edge browser. However, in Chrome it is not the same, when the fields are changed and Edit button is pressed at the bottom of the page. It clears of the entire page and redirects to Add Performance Tests.
This is another behavior which I was experiencing until yesterday and different from what I mentioned in the beginning of the thread.

**Comment by hunkom** [comment]
This may be a bug with fast session expiring. It is recommended to save your configs every 1-2 minutes, to avoid this issue.

**Comment by arozumenko** [comment]
@ankitps1807 @karthikeyans1 any more help required here, or you were able to edit the test?

**Comment by arozumenko** [comment]
seems like everything is fine there
