### ISSUE TITLE
not able to view the test result in reports

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/galloper#79]
I did create a simple JMX to open google and view but can't see any results

[gtest.zip](https://github.com/carrier-io/galloper/files/5161983/gtest.zip)

![image](https://user-images.githubusercontent.com/3865402/91975957-1ffe9f00-ed18-11ea-8ff2-7b18a0716141.png)

**Comment by tokarthik** [comment]
@hunkom any idea about this issue

**Comment by hunkom** [comment]
@tokarthik Actually there are some results in the report. HTTP Request is the name of your sampler in JMeter.

<img width="920" alt="Screenshot 2020-09-02 at 14 41 06" src="https://user-images.githubusercontent.com/46744804/91977085-c3f14600-ed2a-11ea-8a98-f8c50b902ff9.png">
<img width="339" alt="Screenshot 2020-09-02 at 14 42 51" src="https://user-images.githubusercontent.com/46744804/91977092-c5bb0980-ed2a-11ea-9a83-9ce78cebff91.png">

**Comment by hunkom** [comment]
Also looks like post processing doesn't work. It should update the report with some additional info. 
Could you please share logs from post processing task?

<img width="296" alt="Screenshot 2020-09-02 at 14 47 04" src="https://user-images.githubusercontent.com/46744804/91977337-33ffcc00-ed2b-11ea-94c6-14220abb5a15.png">

<img width="2366" alt="Screenshot 2020-09-02 at 14 47 44" src="https://user-images.githubusercontent.com/46744804/91977425-5691e500-ed2b-11ea-8c50-66b213b8cbed.png">

**Comment by tokarthik** [comment]
thanks, it seems db not found 

`
Galloper | Carrier's small guns mount

Add a note...
Clipped from: http://ec2-54-237-78-42.compute-1.amazonaws.com/task/2541c214-05f3-43de-8da0-2e7807f00c03/results
2020-Sep-2 12:25:25
START RequestId: f56197ce-8367-1e5b-53f9-eff9f5d39942 Version: $LATEST
404: {"error":"database not found: \"comparison\""}

Failed connection to ec2-54-237-78-42.compute-1.amazonaws.com, database - comparison
END RequestId: f56197ce-8367-1e5b-53f9-eff9f5d39942
REPORT RequestId: f56197ce-8367-1e5b-53f9-eff9f5d39942
Init Duration: 460.88 ms
Duration: 811.86 ms
Billed Duration: 900 ms
Memory Size: 1536 MB
Max Memory Used: 49 MB


{"statusCode":500,"body":"\"database not found: comparison\""}
{
    "statusCode": 500,
    "body": "\"database not found: comparison\""
}
2020-Sep-2 10:43:22
START RequestId: eea60a5c-b729-1c39-e111-8f2bbff60238 Version: $LATEST
404: {"error":"database not found: \"comparison\""}

Failed connection to ec2-54-237-78-42.compute-1.amazonaws.com, database - comparison
END RequestId: eea60a5c-b729-1c39-e111-8f2bbff60238
REPORT RequestId: eea60a5c-b729-1c39-e111-8f2bbff60238
Init Duration: 382.46 ms
Duration: 165.13 ms
Billed Duration: 200 ms
Memory Size: 1536 MB
Max Memory Used: 42 MB


{"statusCode":500,"body":"\"database not found: comparison\""}
{
    "statusCode": 500,
    "body": "\"database not found: comparison\""
}
2020-Sep-1 16:20:29
START RequestId: 2f8d291b-5f14-1c84-089f-72f5690c0d50 Version: $LATEST
404: {"error":"database not found: \"comparison\""}

Failed connection to ec2-54-237-78-42.compute-1.amazonaws.com, database - comparison
END RequestId: 2f8d291b-5f14-1c84-089f-72f5690c0d50
REPORT RequestId: 2f8d291b-5f14-1c84-089f-72f5690c0d50
Init Duration: 404.85 ms
Duration: 174.46 ms
Billed Duration: 200 ms
Memory Size: 1536 MB
Max Memory Used: 49 MB


{"statusCode":500,"body":"\"database not found: comparison\""}
{
    "statusCode": 500,
    "body": "\"database not found: comparison\""
}
2020-Sep-1 16:18:29
START RequestId: 2a18b257-a47d-1cc4-9268-c433b8057688 Version: $LATEST
404: {"error":"database not found: \"comparison\""}

Failed connection to ec2-54-237-78-42.compute-1.amazonaws.com, database - comparison
END RequestId: 2a18b257-a47d-1cc4-9268-c433b8057688
REPORT RequestId: 2a18b257-a47d-1cc4-9268-c433b8057688
Init Duration: 455.23 ms
Duration: 232.23 ms
Billed Duration: 300 ms
Memory Size: 1536 MB
Max Memory Used: 42 MB


{"statusCode":500,"body":"\"database not found: comparison\""}
{
    "statusCode": 500,
    "body": "\"database not found: comparison\""
}
2020-Sep-1 15:39:54
START RequestId: 8a8bed28-d360-19cf-cf1f-2d2c4a145e7e Version: $LATEST
404: {"error":"database not found: \"comparison\""}

Failed connection to ec2-54-237-78-42.compute-1.amazonaws.com, database - comparison
END RequestId: 8a8bed28-d360-19cf-cf1f-2d2c4a145e7e
REPORT RequestId: 8a8bed28-d360-19cf-cf1f-2d2c4a145e7e
Init Duration: 408.06 ms
Duration: 171.52 ms
Billed Duration: 200 ms
Memory Size: 1536 MB
Max Memory Used: 42 MB


{"statusCode":500,"body":"\"database not found: comparison\""}
{
    "statusCode": 500,
    "body": "\"database not found: comparison\""
}
2020-Sep-1 14:17:57
START RequestId: bc671b77-60e6-1026-9c2b-4d4eaabcd3a9 Version: $LATEST
404: {"error":"database not found: \"comparison\""}

Failed connection to ec2-54-237-78-42.compute-1.amazonaws.com, database - comparison
END RequestId: bc671b77-60e6-1026-9c2b-4d4eaabcd3a9
REPORT RequestId: bc671b77-60e6-1026-9c2b-4d4eaabcd3a9
Init Duration: 395.92 ms
Duration: 172.98 ms
Billed Duration: 200 ms
Memory Size: 1536 MB
Max Memory Used: 42 MB


{"statusCode":500,"body":"\"database not found: comparison\""}
{
    "statusCode": 500,
    "body": "\"database not found: comparison\""
}
2020-Sep-1 14:5:17
START RequestId: 19f8e60d-60a2-1a47-06bf-1070f04bb57d Version: $LATEST
404: {"error":"database not found: \"comparison\""}

Failed connection to ec2-54-237-78-42.compute-1.amazonaws.com, database - comparison
END RequestId: 19f8e60d-60a2-1a47-06bf-1070f04bb57d
REPORT RequestId: 19f8e60d-60a2-1a47-06bf-1070f04bb57d
Init Duration: 445.63 ms
Duration: 114.37 ms
Billed Duration: 200 ms
Memory Size: 1536 MB
Max Memory Used: 42 MB


{"statusCode":500,"body":"\"database not found: comparison\""}
{
    "statusCode": 500,
    "body": "\"database not found: comparison\""
}
2020-Sep-1 11:47:47
START RequestId: 3a24b95e-e4a1-1892-623a-0e4ec0c50528 Version: $LATEST
404: {"error":"database not found: \"comparison\""}

Failed connection to ec2-54-237-78-42.compute-1.amazonaws.com, database - comparison
END RequestId: 3a24b95e-e4a1-1892-623a-0e4ec0c50528
REPORT RequestId: 3a24b95e-e4a1-1892-623a-0e4ec0c50528
Init Duration: 416.12 ms
Duration: 110.11 ms
Billed Duration: 200 ms
Memory Size: 1536 MB
Max Memory Used: 42 MB


{"statusCode":500,"body":"\"database not found: comparison\""}
{
    "statusCode": 500,
    "body": "\"database not found: comparison\""
}
2020-Sep-1 11:37:0
START RequestId: 3e78840d-87cd-1dd9-1986-de9e6f423d47 Version: $LATEST
404: {"error":"database not found: \"comparison\""}

Failed connection to ec2-54-237-78-42.compute-1.amazonaws.com, database - comparison
END RequestId: 3e78840d-87cd-1dd9-1986-de9e6f423d47
REPORT RequestId: 3e78840d-87cd-1dd9-1986-de9e6f423d47
Init Duration: 456.04 ms
Duration: 119.62 ms
Billed Duration: 200 ms
Memory Size: 1536 MB
Max Memory Used: 42 MB


{"statusCode":500,"body":"\"database not found: comparison\""}
{
    "statusCode": 500,
    "body": "\"database not found: comparison\""
}
2020-Aug-26 8:5:28
START RequestId: bab1fecb-83e5-1710-beed-985b135d9cd9 Version: $LATEST
END RequestId: bab1fecb-83e5-1710-beed-985b135d9cd9
REPORT RequestId: bab1fecb-83e5-1710-beed-985b135d9cd9
Init Duration: 407.15 ms
Duration: 35.33 ms
Billed Duration: 100 ms
Memory Size: 1536 MB
Max Memory Used: 49 MB


{"statusCode":500,"body":"\"string indices must be integers\""}
{
    "statusCode": 500,
    "body": "\"string indices must be integers\""
}`

**Comment by hunkom** [comment]
yes, you need to create 2 databases in InfluxDB.

docker exec -ti carrier-influx influx
create database comparison
create database thresholds

**Comment by tokarthik** [comment]
i have created now i can see the DB crated , let me test and come back soon

**Comment by arozumenko** [comment]
@tokarthik any more help required here?

**Comment by tokarthik** [comment]
working thanks
